title: Torlenor.org
email: torlenor at fuu.la
description: >- # this means to ignore newlines until "baseurl:"
  My private page where I am blogging about my coding adventures.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://torlenor.org" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
# theme: minima
# theme: jekyll-theme-midnight
remote_theme: jekyll/minima
plugins:
  - jekyll-feed

minima:
  skin: dark
  social_links:
    - { platform: twitter, user_url: "https://twitter.com/hpsch" }
    - { platform: github,  user_url: "https://github.com/torlenor" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/hans-peter-schadler/" }

show_downloads: false
google_analytics: UA-62820693-2

github:
  repository_url:
  is_project_page: false
